from .Mesher3D.Mesher3D import mesher3D
import shutil
import os
from pycompss.api.task import task
from pycompss.api.parameter import *

#dataPath=path to the file generated by RVE_gen
#simulation_wdir=path to the mesh files will be generated
@task(returns=1)
def mesher(case, h, c, nOfLevels, generateCohesiveElements, simulation_wdir, dataPath):
    simulation_wdir=simulation_wdir+"/msh/"
    os.makedirs(simulation_wdir)

    gmshBinFile = check_environment_variable('gmshBinFile')
    gmsh2alya = check_environment_variable('gmsh2alya')
    
    # Run mesher
    mesher3D(case, gmshBinFile, gmsh2alya, dataPath, simulation_wdir, h, c, nOfLevels, generateCohesiveElements)
    return True

def check_environment_variable(variable_name):
    value = os.environ.get(variable_name)
    if value is not None:
        print(f"The value of {variable_name} is: {value}")
        return value
    else:
        raise Exception(f"Environment variable '{variable_name}' is not set.")
