from .Mesher3D.Mesher3D import mesher3D
import shutil
import os


#dataPath=path to the file generated by RVE_gen
#simulation_wdir=path where the mesh files will be generated
def mesher(case, h, c, nOfLevels, generateCohesiveElements, simulation_wdir, dataPath):
    simulation_wdir=simulation_wdir+"/msh/"
    os.makedirs(simulation_wdir)

    gmshBinFile = os.environ.get('gmshBinFile')

    if gmshBinFile is not None:
        print(f"The value of gmshBinFile is: {gmshBinFile}")
    else:
        raise Exception("Environment variable 'gmshBinFile' is not set.")

    gmsh2alya = os.environ.get('gmsh2alya')

    if gmsh2alya is not None:
        print(f"The value of gmshBinFile is: {gmsh2alya}")
    else:
        raise Exception("Environment variable 'gmshBinFile' is not set.")
    
    # Run mesher
    mesher3D(case, gmshBinFile, gmsh2alya, dataPath, simulation_wdir, h, c, nOfLevels, generateCohesiveElements)


