def writeAlyaDomDat(filePath, fileName, ndime, nmate, npoin, nelem, nboun, kfl_coh, kfl_ori):
    """ Alya caseName.dom.dat file
    """
    
    stream = open(filePath, 'w')

    stream.write('$-------------------------------------------------------------------\n')
    stream.write('DIMENSIONS\n')
    stream.write('  NODAL_POINTS      = %d\n' % npoin)
    stream.write('  ELEMENTS          = %d\n' % nelem)
    stream.write('  BOUNDARIES        = %d\n' % nboun)
    stream.write('  SPACE_DIMENSIONS  = 3\n')
    stream.write('  TYPES_OF_ELEMENTS = HEX08, PEN06\n')
    stream.write('  MATERIALS         = %d\n' % nmate)
    stream.write('  FIELDS            = 1\n')
    if kfl_ori == 'lperm':
        stream.write('    FIELD= 1, DIMENSIONS= %d, ELEMENTS\n' % (9))
    elif kfl_ori == 'uniform':
        stream.write('    FIELD= 1, DIMENSIONS= %d, ELEMENTS\n' % (1))
    stream.write('  END_FIELDS\n')
    stream.write('END_DIMENSIONS\n')
    stream.write('$-------------------------------------------------------------------\n')
    stream.write('STRATEGY\n')
    stream.write('  INTEGRATION_RULE:                OPEN\n')
    stream.write('  DOMAIN_INTEGRATION_POINTS=       0\n')    
    stream.write('  SCALE:                           XSCAL= 1.0 YSCAL= 1.0 ZSCAL= 1.0\n')
    stream.write('  TRANSLATION:                     XTRAN= 0.0 YTRAN= 0.0 ZTRAN= 0.0\n')
    stream.write('  EXTRAPOLATE_BOUNDARY_CONDITIONS: ON\n')
    stream.write('  BOUNDARY_ELEMENT:                ON\n')
    stream.write('END_STRATEGY\n')
    stream.write('$-------------------------------------------------------------------\n')
    stream.write('GEOMETRY\n')
    stream.write('  INCLUDE ./msh/%s.coo.dat\n' % fileName)
    stream.write('  INCLUDE ./msh/%s.ele.dat\n' % fileName)
    stream.write('  INCLUDE ./msh/%s.npe.dat\n' % fileName)
    stream.write('  INCLUDE ./msh/%s.mat.dat\n' % fileName)
    stream.write('  INCLUDE ./msh/%s.bou.dat\n' % fileName)
    if kfl_coh:
        stream.write('  INCLUDE ./msh/%s.cha.dat\n' % fileName)
    stream.write('END_GEOMETRY\n')
    stream.write('$-------------------------------------------------------------------\n')
    stream.write('SETS\n')
    stream.write('  INCLUDE ./msh/%s.set.dat\n' % fileName)
    stream.write('END_SETS\n')
    stream.write('$-------------------------------------------------------------------\n')
    stream.write('BOUNDARY_CONDITIONS\n')
    stream.write('  INCLUDE ./msh/%s.fix.dat\n' % fileName)
    stream.write('END_BOUNDARY_CONDITIONS\n')
    stream.write('$-------------------------------------------------------------------\n')
    stream.write('FIELDS\n')
    stream.write('  INCLUDE ./msh/%s.fie.dat\n' % fileName)
    stream.write('END_FIELDS\n')
    stream.write('$-------------------------------------------------------------------\n')
    
    stream.close()
